
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/NormalFolder/software/CompilingSoftware/toolbox/apps/CLion/ch-0/232.9921.42/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/NormalFolder/software/CompilingSoftware/toolbox/apps/CLion/ch-0/232.9921.42/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/NormalFolder/software/CompilingSoftware/toolbox/apps/CLion/ch-0/232.9921.42/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/NormalFolder/software/CompilingSoftware/toolbox/apps/CLion/ch-0/232.9921.42/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/NormalFolder/software/CompilingSoftware/VisualStudio/VC/Tools/MSVC/14.28.29333/bin/Hostx86/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29336 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.28.29336.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        D:/cityu/finger-tracking/software/leapmotion/leap-example/cmake-build-debug-visual-studio/CMakeFiles/3.26.4/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/NormalFolder/software/CompilingSoftware/toolbox/apps/CLion/ch-0/232.9921.42/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "C:/NormalFolder/software/CompilingSoftware/toolbox/apps/CLion/ch-0/232.9921.42/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/NormalFolder/software/CompilingSoftware/toolbox/apps/CLion/ch-0/232.9921.42/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        Note: including file: D:\\cityu\\finger-tracking\\software\\leapmotion\\leap-example\\cmake-build-debug-visual-studio\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Note: including file: "
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/NormalFolder/software/CompilingSoftware/toolbox/apps/CLion/ch-0/232.9921.42/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/NormalFolder/software/CompilingSoftware/toolbox/apps/CLion/ch-0/232.9921.42/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/cityu/finger-tracking/software/leapmotion/leap-example/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-4mt29k"
      binary: "D:/cityu/finger-tracking/software/leapmotion/leap-example/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-4mt29k"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: D:/cityu/finger-tracking/software/leapmotion/leap-example/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-4mt29k
        
        Run Build Command(s):C:/NormalFolder/software/CompilingSoftware/toolbox/apps/CLion/ch-0/232.9921.42/bin/ninja/win/x64/ninja.exe -v cmTC_6f682 && [1/2] C:\\NormalFolder\\software\\CompilingSoftware\\VisualStudio\\VC\\Tools\\MSVC\\14.28.29333\\bin\\Hostx86\\x64\\cl.exe  /nologo   /DWIN32 /D_WINDOWS  /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FoCMakeFiles\\cmTC_6f682.dir\\CMakeCCompilerABI.c.obj /FdCMakeFiles\\cmTC_6f682.dir\\ /FS -c C:\\NormalFolder\\software\\CompilingSoftware\\toolbox\\apps\\CLion\\ch-0\\232.9921.42\\bin\\cmake\\win\\x64\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c
        [2/2] cmd.exe /C "cd . && C:\\NormalFolder\\software\\CompilingSoftware\\toolbox\\apps\\CLion\\ch-0\\232.9921.42\\bin\\cmake\\win\\x64\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_6f682.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100183~1.0\\x86\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100183~1.0\\x86\\mt.exe --manifests  -- C:\\NormalFolder\\software\\CompilingSoftware\\VisualStudio\\VC\\Tools\\MSVC\\14.28.29333\\bin\\Hostx86\\x64\\link.exe /nologo CMakeFiles\\cmTC_6f682.dir\\CMakeCCompilerABI.c.obj  /out:cmTC_6f682.exe /implib:cmTC_6f682.lib /pdb:cmTC_6f682.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        
      exitCode: 0
...
